<div class="container">

    <div class="home-contact">
            <h1>Contact us</h1>
    </div>

    <section class="about">
        <h2>This is Garden Food</h2>
        <div class="about_inner">
            <article>
                <h3>Our incredible coffee</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            </article>
        </div>

        <div class="about_inner">
            <article>
                <h3>Our awesome shop</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            </article>
        </div>
    </section>

    <section class="contact-map"> 
        <div class="contact">
            <div>
                <h3>Address</h3>
                <p>210 Williams Avenue</p>
                <p>32456</p> 
                <p>PORT SAINT JOE</p>
            </div>

            <div>
                <h3>Phone</h3>
                <p>0115 9373150</p>
            </div>

            <div>
                <h3>Email</h3>
                <p><a href= "mailto:tigf@gmail.com">thisisgardenfood@gmail.com</a></p>
            </div>
        </div>
        
        <div class="map">
            <h3>Find Us</h3>
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3989.818320343149!2d0!3d0!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x889497e857052e05%3A0xe2ed30236da20b93!2sT.I.G.F%20(this%20is%20garden%20food)!5e0!3m2!1sfr!2sus!4v1620850303470!5m2!1sfr!2sus" class="map-google" allowfullscreen="" loading="lazy">
            </iframe>    
        </div>

        <div class="hours">
            <h3>Opening Hours</h3>
            <ul>
                <li>Mon: 07.30 - 20:00 Hrs</li>
                <li>Tue: 07.30 - 20:00 Hrs</li>
                <li>Wed: 07.30 - 20:00 Hrs</li>
                <li>Thu: 07.30 - 20:00 Hrs</li>
                <li>Fri: 07.30 - 20:00 Hrs</li>
                <li>Sat: 08.00 - 19:00 Hrs</li>
                <li>Sun: 09.30 - 18:00 Hrs</li>
            </ul>
        </div> 
    </section> 
</div>
