
<section class = "row home-page-intro">
    <div class = "column home-page-header">
        <h1>This Is Garden Food</h1>

        <div class="column home-page-baseline">
            <img src="public/data/img/planet-hands.png" alt="This is Garden Food">
            <p>Tasty and home made food</p>
        </div>
    </div>   
</section>

<section class = "home-page-show">
    <div class="one">
        <div class="lg-img">
            <img src="public/data/img/img1.jpg" alt="Chef David" class="grid-img">
        </div>
        <div class = "column slideshow-text">
            <h2>This Is Garden Food</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro dolores ut reiciendis nemo numquam, tempora culpa officia qui explicabo natus libero minima voluptate quas quasi deserunt quibusdam sequi magnam tenetur! Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro dolores ut reiciendis nemo numquam, tempora culpa officia qui explicabo natus libero minima voluptate quas quasi deserunt quibusdam sequi magnam tenetur!
            </p>
            <a class="link" href ="<?= URL; ?>menu">See the Menu</a>
        </div>
    </div>

    <div class="two">
        <div class="lg-img inverse-left">
            <img src="public/data/img/botania.jpg" alt="Restaurant TIGF" class="grid-img">
        </div>
        <div class = "column slideshow-text inverse-right">
            <h2>This Is Garden Food</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro dolores ut reiciendis nemo numquam, tempora culpa officia qui explicabo natus libero minima voluptate quas quasi deserunt quibusdam sequi magnam tenetur! Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro dolores ut reiciendis nemo numquam, tempora culpa officia qui explicabo natus libero minima voluptate quas quasi deserunt quibusdam sequi magnam tenetur!
            </p>
        </div>
    </div>

    <section class = "bloc-id">
        <div>
            <img src="public/data/img/David.png" alt="Chef David" class = "round-img">
        </div>   
        <div >
            <h2 class="h2-white">The Chef</h2>
            <p>I choose carefully the raw materials fresh and local to concoct a tasty dish.<span> Chef David</span></p>
            <a class="link" href="<?= URL; ?>contact">Contact</a>
        </div>
</section>


    <div class="three">
        <div class="lg-img">
            <img src="public/data/img/img3.jpg" alt="Dish" class="grid-img">
        </div>
        <div class = "column slideshow-text">
            <h2>This Is Garden Food</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro dolores ut reiciendis nemo numquam, tempora culpa officia qui explicabo natus libero minima voluptate quas quasi deserunt quibusdam sequi magnam tenetur! Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro dolores ut reiciendis nemo numquam, tempora culpa officia qui explicabo natus libero minima voluptate quas quasi deserunt quibusdam sequi magnam tenetur!
            </p>
            <a class="link" href="<?= URL; ?>menu">See the Menu</a>
        </div>
    </div>
</section>


