<section id="menu-list" class="section-padding">
    <div class="content-wrapper">
        <div class="bloc-menu">
            <div class="menu-filters">
                <h1>Menu List</h1>
                <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam. </p>
            </div>
                <!-- Filtres -->
            <div class="menu-filters marb-35" id="menu-filters">
                <ul>
                  <li><button id="filterAll" class="filter active">Show all</button></li>
                  <li><button id="filterStarter" class="filter">Starters</button></li>
                  <li><button id="filterDish" class="filter">Dishes</button></li>
                  <li><button id="filterDessert" class="filter">Desserts</button></li>
                </ul>
            </div>
            
           <!-- Serach-->
            <div class="search-filter">
                <input type="text" id="idSearchFilter" placeholder="Rechercher un plat" />
                <button id="searchRefresh" class="more" type="submit">Rafraichir la recherche</button>            
            </div>

            <div class = "menu-wrapper" id="menu-wrapper">
                <!-- Starters -->
                <div id = "starters" class="starters menu-restaurant">
                    <h2 class="titre-menuList">Starters</h2>
                    <?php foreach($categoryStarters as $categoryStarter) : ?>
                        <div class="column single-menu">
                            <img src="<?= htmlspecialchars($categoryStarter->dish_img, ENT_QUOTES, 'UTF-8'); ?> " alt="">
                            <div class="menu-content">
                                <h4 class = "menu-subtitle"><?= htmlspecialchars($categoryStarter->dish_name, ENT_QUOTES, 'UTF-8'); ?></h4>
                                <span><?= htmlspecialchars($categoryStarter->dish_content, ENT_QUOTES, 'UTF-8'); ?></span>
                                <p><?= htmlspecialchars($categoryStarter->dish_price, ENT_QUOTES, 'UTF-8'); ?> $</p>
                            </div>
                        </div>
                    <?php endforeach ?> 
                </div>

                <!-- Plats -->
                <div id = "dishes" class="plats menu-restaurant">
                    <h2 class="titre-menuList">Plats</h2>
                    <?php foreach($categorieMains as $categorieMain) : ?>
                        <div class="column single-menu">
                            <img src="<?= htmlspecialchars($categorieMain->dish_img, ENT_QUOTES, 'UTF-8'); ?> " alt="">
                            <div class="menu-content">
                                <h4 class = "menu-subtitle"><?= htmlspecialchars($categorieMain->dish_name, ENT_QUOTES, 'UTF-8'); ?></h4>
                                <span><?= htmlspecialchars($categorieMain->dish_content, ENT_QUOTES, 'UTF-8'); ?></span>
                                <p><?= htmlspecialchars($categorieMain->dish_price, ENT_QUOTES, 'UTF-8'); ?> $</p>
                            </div>
                        </div>
                    <?php endforeach ?> 
                </div>

                <!-- Desserts -->
                <div id = "desserts" class="desserts menu-restaurant">
                    <h2 class="titre-menuList">Desserts</h2>
                    <?php foreach($categoryDesserts as $categoryDessert) : ?>
                        <div class="column single-menu">
                            <img src="<?= htmlspecialchars($categoryDessert->dish_img, ENT_QUOTES, 'UTF-8'); ?> " alt="">
                            <div class="menu-content">
                                <h4 class = "menu-subtitle"><?= htmlspecialchars($categoryDessert->dish_name, ENT_QUOTES, 'UTF-8'); ?></h4>
                                <span><?= htmlspecialchars($categoryDessert->dish_content, ENT_QUOTES, 'UTF-8'); ?></span>
                                <p><?= htmlspecialchars($categoryDessert->dish_price, ENT_QUOTES, 'UTF-8'); ?> $</p>
                            </div>
                        </div>
                    <?php endforeach ?> 
                </div>
            </div>
        </div>
    </div>
</section>
