<div class="container">
    <!-- add menu form -->
    <div class="box-input">
        <div class = "add-dash">
            <h3 class="text-align-center">Editer un Menu</h3>
            <form action="<?= URL; ?>dashboard/updatemenu" method="POST">
                <div class="box-input lg">
                    <label> Nom du plat:</label>
                    <input autofocus type="text" name="dish_name" value="<?= htmlspecialchars($menu->dish_name, ENT_QUOTES, 'UTF-8'); ?>" required />
                </div>
                <div class="box-input">
                    <label> Prix:</label>
                    <input type="number" name="dish_price" value="<?= htmlspecialchars($menu->dish_price, ENT_QUOTES, 'UTF-8'); ?>" required />
                </div>
                <div class="box-input">
                    <label> Contenu:</label>
                    <input type="text" name="dish_content" value="<?= htmlspecialchars($menu->dish_content, ENT_QUOTES, 'UTF-8'); ?>" />
                </div>
                <div class="box-input">
                    <label> Options:</label>
                    <input type="text" name="dish_option" value="<?= htmlspecialchars($menu->dish_option, ENT_QUOTES, 'UTF-8'); ?>" />       
                </div>
                <div class="box-input">
                    <label> Url de l'image:</label>
                    <input type="text" name="dish_img" value="<?= htmlspecialchars($menu->dish_img, ENT_QUOTES, 'UTF-8'); ?>" />  
                </div>
                <div class="box-input">
                    <label> Categorie:</label>
                    <input type="number" name="dish_category" value="<?= htmlspecialchars($menu->dish_category, ENT_QUOTES, 'UTF-8'); ?>" />  
                </div>
                <!-- Non visible - Hidden -->
                <div class="box-input">
                    <input type="hidden" name="id" value="<?= htmlspecialchars($menu->id, ENT_QUOTES, 'UTF-8'); ?>" />
                </div>
                <input type="submit" name="submit_update_menu" value="Mettre à jour" />
            </form>
        </div>
    </div>
</div>

