<div class="container">
    <h2 class="text-align-center">Tableau de bord</h2>
    <div class="box-input">
        <div class = "add-dash">
            
            <form action="<?= URL; ?>userAdmin/addNewUser" method="POST">
                <h3 class="text-align-center">Ajouter un administrateur</h3>
                <div class="box-input lg">
                    <label> Nom d'utilisateur:</label>
                    <input type="text" name="username" value="" required/>
                </div>
                
                <div class="box-input lg">
                    <label> Email de l'utilisateur:</label>
                    <input type="email" name="usermail" value="" required/>
                </div>
                
                <div class="box-input">
                    <label> Mot de passe:</label>
                    <input type="text" name="password" value="" required/>
                </div>
                
                <input id="alertUser" class="more" type="submit" name="submit_add_user" value="Ajouter" />
                

            </form>
    
            <div class = "AdminTable-user">
                <h3 class="text-align-center">Liste des administrateurs</h3>
                <table class=”events-table”>
                    <thead>                      
                        <tr>
                            <th class=”event-1”>Nom</th>
                            <th class=”event-2”>Email</th>
                            <th class=”event-3”>Mot de passe</th>
                            <th class=”event-6”>Supprimer</th>
                            <th class=”event-7”>Modifier</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($users as $user) { ?>
                            <tr>
                                <td class = "tab-first-name" data-label="Nom"><?= htmlspecialchars($user->username, ENT_QUOTES, 'UTF-8'); ?></td>
                                <td data-label="Email"><?= htmlspecialchars($user->usermail, ENT_QUOTES, 'UTF-8'); ?></td>
                                <td data-label="Mot de passe"><?= htmlspecialchars($user->password, ENT_QUOTES, 'UTF-8'); ?></td>
                                <td data-label="Supprimer"><a class = "button-rajout" href="<?= URL . 'dashboard/deleteuser/' . htmlspecialchars($user->id, ENT_QUOTES, 'UTF-8'); ?>">delete</a></td>
                                <td data-label="Modifier"><a class = "button-rajout" href="<?= URL . 'dashboard/edituser/' . htmlspecialchars($user->id, ENT_QUOTES, 'UTF-8'); ?>">edit</a></td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
    
    
        <div class = "AdminTable-newsleters">
            <h3 class="text-align-center">Inscription Newsletters</h3>
            <table class=”events-table”>
                <thead>                      
                    <tr>
                        <th class=”event-1”>ID</th>
                        <th class=”event-1”>Nom</th>
                        <th class=”event-2”>Email</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($newsletters as $newsletter) { ?>
                        <tr>
                            <td class = "tab-first-name" data-label="Id"><?= htmlspecialchars($newsletter->id, ENT_QUOTES, 'UTF-8'); ?></td>
                            <td class = "tab-first-name" data-label="Nom"><?= htmlspecialchars($newsletter->email, ENT_QUOTES, 'UTF-8'); ?></td>
                            <td data-label="Email"><?= htmlspecialchars($newsletter->nom, ENT_QUOTES, 'UTF-8'); ?></td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>

        <div class="box-input"></div>
            <div class = "add-dash">
                <form action="<?= URL; ?>dashboard/addmenu" method="POST">
                    <h3 class="text-align-center">Ajouter un plat</h3>
                    
                    <div class="box-input lg">
                        <label> Nom du plat:</label>
                        <input type="text" name="dish_name" value="" required placeholder="Exemple: Hamburger" />
                    </div>
                    <div class="box-input">
                        <label> Prix:</label>
                        <input type="number" name="dish_price" value="" required placeholder="Exemple: 10"  />
                    </div>
                    <div class="box-input lg">
                        <label> Contenu:</label>
                        <input type="text" name="dish_content" value="" placeholder="Exemple: Beef, Cheddar, Salad" />
                    </div>
                    <div class="box-input lg">
                        <label> Options:</label>
                        <input type="text" name="dish_option" value="" placeholder="Exemple: Beef or Chiken" />
                    </div>
                    <div class="box-input">
                        <label> Url de l'image:</label>
                        <input type="text" name="dish_img" value="" />
                    </div>
                    
                    <div class="box-input">
                        <label> Catégorie:</label>
                        <input type="number" name="dish_category" value="" min="1" max="3" required placeholder="1=Starters, 2=Plats, 3=Desserts" />
                    </div>
                    <input class="more" type="submit" name="submit_add_menu" value="Ajouter" />
                </form>
            </div>
    
        <div class = "sous-dash">
            <div class="sous-dash-box text-align-center">
                <h4>Total de plats</h4>
                <h4><?= $amount_of_menus; ?></h4> 
            </div> 
            <div class="sous-dash-box text-align-center">
                <h4>Nombre d'entrées</h4>
                <h4><?= $amount_of_cat_starters; ?></h4> 
            </div> 
            <div class="sous-dash-box text-align-center">
                <h4>Nombre de plats</h4>
                <h4><?= $amount_of_cat_mains; ?></h4> 
            </div> 
            <div class="sous-dash-box text-align-center">
                <h4>Nombre de desserts</h4>
                <h4><?= $amount_of_cat_desserts; ?></h4> 
            </div> 
        </div>
    
        <div class = "AdminTable">
            <h3 class="text-align-center">Liste des plats</h3>
            <table class=”events-table”>
                <thead>                      
                    <tr>
                        <th class=”event-1”>Id</th>
                        <th class=”event-1”>Nom du plat</th>
                        <th class=”event-2”>Contenu</th>
                        <th class=”event-3”>Prix</th>
                        <th class=”event-4”>Url Image</th>
                        <th class=”event-5”>Categorie du plat</th>
                        <th class=”event-6”>Supprimer</th>
                        <th class=”event-7”>Modifier</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($menus as $menu) { ?>
                        <tr>
                            <td class = "tab-first-name" data-label="Id"><?php if (isset($menu->id)) echo htmlspecialchars($menu->id, ENT_QUOTES, 'UTF-8'); ?></td>
                            <td class = "tab-first-name" data-label="Nom"><?php if (isset($menu->dish_name)) echo htmlspecialchars($menu->dish_name, ENT_QUOTES, 'UTF-8'); ?></td>
                            <td data-label="Contenu"><?php if (isset($menu->dish_content)) echo htmlspecialchars($menu->dish_content, ENT_QUOTES, 'UTF-8'); ?></td>
                            <td data-label="Prix"><?php if (isset($menu->dish_price)) echo htmlspecialchars($menu->dish_price, ENT_QUOTES, 'UTF-8'); ?></td>
                            <td data-label="Image"><?php if (isset($menu->dish_img)) echo htmlspecialchars($menu->dish_img, ENT_QUOTES, 'UTF-8'); ?></td>
                            <td data-label="Cateégorie"><?php if (isset($menu->category_name)) echo htmlspecialchars($menu->category_name, ENT_QUOTES, 'UTF-8'); ?></td>
                            <td data-label="Supprimer"><a class = "button-rajout" href="<?= URL . 'dashboard/deletemenu/' . htmlspecialchars($menu->id, ENT_QUOTES, 'UTF-8'); ?>">delete</a></td>
                            <td data-label="Modifier"><a class = "button-rajout" href="<?= URL . 'dashboard/editmenu/' . htmlspecialchars($menu->id, ENT_QUOTES, 'UTF-8'); ?>">edit</a></td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
