
<footer>
    <div class = "conteneur">
        <div class = "footer-box">
            <div class="footer-block">
                <ul class="footer-list">
                    <li><a href="<?= URL; ?>">Home</a></li>
                    <li><a href="<?= URL; ?>menu">Menu</a></li>
                    <li><a href="<?= URL; ?>contact">Contact</a></li>
                </ul>
            </div>

            <div class="footer-block">
                <div class = "adress">
                    <h5>Adress</h5>
                    <p>210 Williams Avenue</p>
                    <p>32456</p>
                    <p>PORT SAINT JOE</p>
                </div>    
            </div>
            
            <div class="footer-block">
                <form action="<?= URL; ?>user/addNewsletters" method="POST">
                    <h5>Newsletters</h5>
                    <div class="champs">
                        <label>Your first name:</label>
                        <input type="text" name="nom" required>
                    </div>
                    <div class="champs">
                        <label>Your Email :</label>
                        <input type="email" name="email"  required>
                    </div>

                    
                    <input class="more form" type="submit" name="submit_add_newsletters" value="Envoyer">
                </form>
            </div>
        </div>
    
    </div>
    
    <div class="footer-icones">
                <ul class="favicon">
                    <li class="favicon-reseau"><a href="#"><i class="fa fa-facebook"></i></a></li>
                    <li class="favicon-reseau"><a href="#"><i class="fa fa-twitter"></i></a></li>
                    <li class="favicon-reseau"><a href="#"><i class="fa fa-instagram"></i></a></li>
                </ul>
            </div>


    <div class="footer-mentions">
        <div class = "mention">
            <p>© 2021 <a href="http://thisisgardenfood.com/" target="_blank">This is Garden Food</a></p>
        </div>
    </div>
</footer>






    <script src="//code.jquery.com/jquery-3.5.1.min.js"></script>

    <!-- JavaScript -->
    <script src="<?= URL; ?>js/menuApp.js"></script>
    <script src="<?= URL; ?>js/search.js"></script>
    <script src="<?= URL; ?>js/application.js"></script>

    

</body>
</html>
