<!DOCTYPE html>
<html lang="zxx">
<head>
    <meta charset="utf-8">
    <title>TIGF</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- CSS -->
    <link href="<?= URL; ?>css/globalsheet.css" rel="stylesheet">
    <link href="<?= URL; ?>css/stylesheet.css" rel="stylesheet">
    
    <!--     Fonts     -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Yusei+Magic&display=swap">    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
    <!--     Script     -->
    <script src="https://kit.fontawesome.com/e06876c6bf.js" crossorigin="anonymous"></script>
    <script src ="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    
    <!--     Script  JQUERY   -->
    <script src = "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

</head>
<body>
    <!-- navigation -->
    <header>
        <!-- navigation -->
        <div class="navigation">
            <div class="left">
                <a href="<?= URL; ?>">Home</a>
                <a href="<?= URL; ?>menu">Menu</a>
                <a href="<?= URL; ?>contact">Contact</a>
            </div>
            
            <div class="right">
                <a href="<?= URL; ?>login">Login</a>
            </div>
        </div>    

    </header>